# Generated by Django 3.2.5 on 2021-07-30 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200, null=True)),
                ('bankType', models.CharField(choices=[('P', 'Private'), ('G', 'Gobernment')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=80)),
                ('lastName', models.CharField(max_length=80)),
                ('birthDate', models.DateField()),
                ('age', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=80, validators=[django.core.validators.EmailValidator(allowlist=['prueba.com'])])),
                ('phone', models.CharField(max_length=20, null=True)),
                ('clientType', models.CharField(choices=[('N', 'Natural'), ('L', 'Legal')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('minPayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maxPayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('termsOfCredits', models.PositiveIntegerField()),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('creditType', models.CharField(choices=[('A', 'Auto'), ('M', 'Mortgage'), ('C', 'Commercial')], max_length=1)),
                ('bankOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bank')),
                ('clientOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
